server.port: ${SERVER_PORT:8082}

symbols-file-path: ${SYMBOL_FILE_PATH:}

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: create-drop

spring.datasource:
  platform: h2
  url: jdbc:h2:mem:stock-watchlist

spring.h2.console:
  enabled: true
  settings:
    web-allow-others: true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

cors.origins: ${CORS_ORIGINS:http://localhost:3000}